### ISSUE TITLE
Migration to version 10.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/project#196]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0
# Modules to migrate
- [ ] analytic_hours_block
- [ ] project_analytic_line_view
- [ ] project_baseuser
- [ ] project_categ
- [ ] project_categ_issue
- [ ] project_classification
- [x] project_closing - By @Jerther - #271
- [x] project_description - By @astirpe  - #203 
- [x] project_double_alias - By @pedrobaeza - #305 
- [ ] project_functional_block
- [x] project_gtd - By @mmequignon - #308 
- [ ] project_issue_baseuser
- [ ] project_issue_code <s>- By @thinkwelltwd - #244 </s>
- [ ] project_issue_task
- [x] project_issue_timesheet_time_control - By @luismontalba - #269 
- [x] project_recalculate - By @pedrobaeza - #291 
- [ ] project_service_type
- [ ] project_sla - By @OpenCode - #361 
- [ ] project_stage_state
- [x] project_task_code - By @kellylougheed - #213
- [x] project_task_default_stage - By @astirpe - #201 
- [x] project_task_materials > project_task_material - By @chienandalu - #251
- [x] project_task_materials_stock > project_task_material_stock - By @cubells - #288  
- [x] project_timeline - By @carlosdauden - #297 
- [x] project_timesheet_time_control - By @luismontalba - #266 
- [ ] project_timesheet_analytic_partner
- [x] sale_order_project - By @Abranes - #377 
- <s>[ ] service_desk</s> (#174 must be refactored in 9.0)
- <s>[ ] service_desk_issue</s>  (#174 must be refactored in 9.0)

**Comment by astirpe** [comment]
Porting project_task_default_stage #201

**Comment by astirpe** [comment]
Porting project_description #203

**Comment by lasley** [comment]
@pedrobaeza please tag @kellylougheed to project_task_code

**Comment by pedrobaeza** [comment]
Done, or as I see she knows latin, "opus factum est" :stuck_out_tongue:

**Comment by Jerther** [comment]
Porting project_closing #271

**Comment by lasley** [comment]
`project_task_code` has been merged & can be checked off

**Comment by Jerther** [comment]
`project_closing` has also been merged.

**Comment by martintorresvm** [comment]
@elicoidal @seb-elico Think we need made the effort for `project_classification`. What do you think?

**Comment by elicoidal** [comment]
@victormartinelicocorp Most important for BR is the parenting which is only a small part of the classification

**Comment by OpenCode** [comment]
I'm working on project_sla

**Comment by OpenCode** [comment]
project_sla PR https://github.com/OCA/project/pull/361

**Comment by sudhir-erpharbor** [comment]
Why project_task_delegate is not in the list and is not migrated? Is there any specific reason for that?
@pedrobaeza

**Comment by pedrobaeza** [comment]
@sudhir-erpharbor because the module was not in v9 when the branches were created. We can add it if you want to migrate it and consider it's still needed.
