### ISSUE TITLE
Migration to version 11.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/project#325]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0

# Modules to migrate

- [ ] analytic_hours_block - By @mpanarin - #484 
- [ ] project_analytic_line_view
- [ ] project_baseuser
- [x] project_categ > project_category - By @cubells - #460
- [ ] project_categ_issue
- [ ] project_classification
- [x] ~~project_closing - By @Jerther - #328~~ It has been finally removed as it's included in core - #353
- [x] project_department - By @arkostyuk - #351 
- [x] project_description - By @emagdalenaC2i - #345  
- [x] ~~project_double_alias~~ - Not needed anymore
- [ ] project_functional_block
- [ ] project_gtd - By @dsasoftware - #390
- [x] ~~project_issue_baseuser~~ Not needed anymore
- [x] ~~project_issue_code~~ Not needed anymore
- [x] ~~project_issue_task~~ Not needed anymore
- [x] ~~project_issue_timesheet_time_control~~ Not needed anymore
- [ ] project_model_to_task
- [ ] project_recalculate
- [ ] project_service_type
- [ ] project_sla
- [x] project_stage_closed - By @ernestotejeda - #389 
- [x] project_stage_state - By @rodrigets - #365 
- [x] project_task_add_very_high - ~~By @emagdalenaC2i - #340~~ By @astirpe - #343 
- [x] project_task_category - ~~By @igallart - #393~~ Integrated in project_category
- [x] project_task_code - By @rodrigets - #363 
- [x] project_task_default_stage - By @novawish - #349 
- [x] project_task_dependency - By @PCatinean - #385 
- [x] project_task_digitized_signature - By @cubells - #507 
- [x] project_task_material - By @BT-ccebrian - #382 
- [x] project_task_material_stock - By @cubells - #432 
- [ ] project_task_material_analytic_partner
- [ ] project_task_material_stock
- [x] project_task_pull_request - By @mstuttgart - #412 
- [x] project_task_send_by_mail - By @cubells - #431
- [x] project_timeline - By @Maartincm - #376
- [ ] project_timesheet_analytic_partner
- [ ] project_timesheet_currency - By @arkostyuk - #350 
- [x] project_timesheet_time_control - By @ernestotejeda - #397 
- [ ] project_wbs - By @aheficent #416 
- [ ] sale_order_project - By @aitorbouzas - #395
- [ ] service_desk
- [ ] service_desk_issue

**Comment by Jerther** [comment]
project_closing ongoing at https://github.com/OCA/project/pull/328

**Comment by emagdalenaC2i** [comment]
I will try to migrate project_description #330

**Comment by emagdalenaC2i** [comment]
project_task_add_very_high #340

**Comment by astirpe** [comment]
@emagdalenaC2i it seems you are not working anymore on the porting of the modules (I'm noticing that you removed your local copy of the repository). It that the case?

**Comment by emagdalenaC2i** [comment]
No, I was just sorting all the repositories in GitHub.
This module should be available for migration in a few days. Sorry for the delay

**Comment by astirpe** [comment]
@emagdalenaC2i I made some small extra development on module _project_task_add_very_high_, and I was also ready to propose it to OCA, but then I saw you were working on the same module.

Anyway I could make a new PR right now. Is that ok if I open a different pull request for _project_task_add_very_high_ that replace yours?

**Comment by emagdalenaC2i** [comment]
Sure, go on.
I will test it and close this one if it works fine

**Comment by astirpe** [comment]
New PR for `project_task_add_very_high`: https://github.com/OCA/project/pull/343
Supersedes https://github.com/OCA/project/pull/340

**Comment by emagdalenaC2i** [comment]
#347 [ADD] project_parent_task_filter 
I don´t know if it is very simple, because it is only a filter. But it will be very useful to me and all the people that use parent tasks

**Comment by pedrobaeza** [comment]
@emagdalenaC2i being a new module, it shouldn't be in this list.

**Comment by novawish** [comment]
`project_task_default_stage` is migrating at https://github.com/OCA/project/pull/349

**Comment by ghost** [comment]
Working on `project_timesheet_currency`

**Comment by pedrobaeza** [comment]
OK, noted

**Comment by ghost** [comment]
On `project_department`

**Comment by rodrigets** [comment]
Working on `project_stage_state`

**Comment by Maartincm** [comment]
project_timeline: #376

**Comment by BT-ccebrian** [comment]
Working on project_task_material

**Comment by ghost** [comment]
Working on `project_task_material`

**Comment by SalahAdDin** [comment]
Asking for `sale_order_project`.

**Comment by mstuttgart** [comment]
@pedrobaeza project_task_pull_request https://github.com/OCA/project/pull/412

**Comment by devang-dreambits** [comment]
I am migrating module project_task_category with PR #418

**Comment by pedrobaeza** [comment]
There's already another migration in #393. Please review that one instead.

**Comment by emagdalenaC2i** [comment]
@pedrobaeza I don't know if project_categ is needed anymore because there is project_category - By @cubells - #460 already merged

Please, add to the list project_task_send_by_mail - By @cubells - #431 

There is a PR for the migration of sale_order_project - By @aitorbouzas - #395 

There is a PR for the migration of project_gtd - By @dsasoftware - #390

**Comment by emagdalenaC2i** [comment]
Please, check project_task_category - By @igallart - #393 that is integrated in project_categ > project_category - By @cubells - #460
