### ISSUE TITLE
Migration to version 16.0

### ISSUE THREAD

**Issue by sbidoul** [OCA/project#988]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0

# Modules to migrate

- [x] project_administrator_restricted_visibility - By @edlopen - #1222
- [x] project_department - By @aiendry-aktivsoftware - #1007
- [x] project_duplicate_subtask - By @uncannycs - #1011
- [ ] project_forecast_line - By @martiqubiq - #1140
- [ ] project_forecast_line_bokeh_chart
- [ ] project_forecast_line_holidays_public
- [x] project_hr - By @pilarvargas-tecnativa - #1117
- [x] project_key - By @vincent-hatakeyama - #1210
- [x] project_list - By @otmanelagy - #1004
- [ ] project_milestone
- [x] project_parent - By @naglis - #1103
- [x] project_parent_task_filter - By @emagdalenaC2i - #1035
- [ ] project_purchase_analytic_global
- [x] project_purchase_link - By @AnizR - #1061
- [x] project_risk - By @HeliconiaSolutions - #1381
- [x] project_role - By @leemannd - #1049
- [x] project_sequence - By @NICO-SOLUTIONS - #1155
- [x] project_status - By @atularvind - #1282
- [x] project_stock - By @RabbitJon-S73 - #1052
- [x] project_stock_product_set - By @victoralmau - #1200
- [x] project_task_add_very_high - By @BT-apadron - #1015
- [x] project_task_code - By @robinkeunen - #1209
- [x] project_task_default_stage - By @uncannycs - #1014
- [x] ~~project_task_dependency~~ Not needed. Feature already in core.
- [x] project_task_description_template - By @Tisho99 - #1360
- [x] project_task_material - By @manuelregidor - #1151
- [ ] project_task_milestone
- [x] project_task_note - By @carolinafernandez-tecnativa - #1240
- [x] project_task_personal_stage_auto_fold - By @emagdalenaC2i - #1037
- [x] project_task_project_required - By @maisim - #1304
- [x] project_task_pull_request - By @Volodiay622 - #1208
- [x] project_task_recurring_activity - By @PicchiSeba - #1323
- [x] project_task_stage_state - By @AungKoKoLin1997 - #1228
- [x] project_template - By @Mantux11  - #1002
- [x] project_timeline - By @bvanjeelharia - #1089
- [x] project_timeline_hr_timesheet - By @Yadier-Tecnativa - #1116
- [x] ~~project_timeline_task_dependency~~ Already included in `project_timeline`
- [x] project_timesheet_time_control - By @stefan-tecnativa - #1148

Missing module? Check https://github.com/OCA/maintainer-tools/wiki/%5BFAQ%5D-Missing-modules-in-migration-issue-list

**Comment by Mantux11** [comment]
Migrating to v16. project_template: #1002

**Comment by yankinmax** [comment]
`project_forecast_line` is migrated here: https://github.com/OCA/project/pull/1001

**Comment by AnizR** [comment]
Hello, project_purchase_link is migrated on this pr #1061

**Comment by RikiBalthazar** [comment]
project_timesheet_time_control is missing to migrate?

**Comment by naglis** [comment]
`project_parent`: #1103

**Comment by rauldb-br** [comment]
> project_timesheet_time_control is missing to migrate?

I think it is Missing on migrate module list, any one can verify this?

**Comment by pedrobaeza** [comment]
Being in the migration list won't speed up its migration. If you have a PR migrating it, then from the PR a command can be launched to include it here.

**Comment by angelmoya** [comment]
Hi @sbidoul ,

can you cancel or cross project_task_milestone module, as this relation is already in version 16.0

https://github.com/odoo/odoo/blob/5e1b3fd6103239f4ca5a10c3b302fe51f313171b/addons/project/models/project_milestone.py#L22

**Comment by angelmoya** [comment]
Hi @sbidoul,

you can also cancel or cross project_task_dependency, as was deprecated since version 15.0, and last version introduces migration script.

https://github.com/OCA/project/pull/892

**Comment by QubiQBcn** [comment]
working on project_department

**Comment by martiqubiq** [comment]
working on project_forecast_line https://github.com/OCA/project/pull/1140

**Comment by jaenbox** [comment]
Migration [[16.0][MIG] project_status](https://github.com/OCA/project/pull/1124)

**Comment by pausanchezqubiq** [comment]
Working on project_purchase_analytic_global

**Comment by valjaro** [comment]
working on/ project_task_stage_state https://github.com/OCA/project/pull/1126

**Comment by valjaro** [comment]
working on / project_task_pull_request https://github.com/OCA/project/pull/1137

**Comment by punt-sistemes-salva** [comment]
working in project_purchase_analytic_global

**Comment by valjaro** [comment]
working on /project_task_material https://github.com/OCA/project/pull/1139

**Comment by NICO-SOLUTIONS** [comment]
Migrating to v16. project_sequence: #1155

**Comment by EmilioPascual** [comment]
Working on sale_project_copy_tasks

**Comment by edlopen** [comment]
Hello!
I have migrated project_administrator_restricted_visibility from 15.0 to 16.0 
https://github.com/OCA/project/pull/1222
Could anyone add it to the list please?

**Comment by victor-champonnois** [comment]
It seems that the link between task and milestone is standard in Odoo 16. So `project_task_milestone` does not need to be ported. 
`project_milestone` is standard since 15.0, so I think it should also be removed from the list. 

The milestone tree view exists in Odoo 16, but there is no menuitem to access it. Maybe a module to add this access is necessary ?
Edit : done here : https://github.com/OCA/project/pull/1258

**Comment by maisim** [comment]
working on project_task_project_required https://github.com/OCA/project/pull/1304

**Comment by etoimene** [comment]
I am noticing that project_wbs is not on the migration list. Latest version is for 15.0.
Anyone working on it?
